---
# Description of the types of training available in the database
- types:
  - name: シナリオに基づいた演習
    category: scenarios
  - name: トピックに基づいた演習 [N/A]
    category: topics

# Description of the scenarios available in the training database
- scenarios:

  # Scenario based on the US National Institute of Standards and Technology
  # (NIST) Guide on Information Security Testing and Assessment
  - name: 情報セキュリティテスト＆評価
    levels:
      - name: レベル 1 （イージー）
        content: NIST-level1-content-ja.yml
        specification: NIST-level1-range.yml
      - name: レベル 2 （ミディアム）[N/A]
      - name: レベル 3 （ハード）[N/A]

  # Scenario based on general guidelines for incident response
  - name: インシデント検出＆レスポンス [N/A]
    levels:
      - name: レベル 1（検出）[N/A]
      - name: レベル 2（捜査）[N/A]
      - name: レベル 3（対応）[N/A]
